version: '3.9'
services:
  test:
    build: .
    image: wechat-bot:latest
    restart: always
    ports:
      - 5900:5900
    environment:
      - ENABLED_X11VNC=yes
    extra_hosts:
      - "master.io:192.168.0.64"